### ISSUE TITLE
Cannot find 'cost' table in MIMIC-iv 2.2 version

### ISSUE THREAD

**Issue by satyakesav** [glee4810/ehrsql-2024#1]
Hi,

I can't find the table named 'cost' (mentioned in the data/mimic_iv/tables.json file) in the MIMIC-IV dataset downloaded from here: https://physionet.org/content/mimiciv/2.2/

Can you please check if this is an issue?

**Comment by glee4810** [comment]
You are correct. The original MIMIC-IV database does not have the cost table. To handle cost-related questions regarding EHR, the preprocessing code on this repo will create a synthetic cost table (OMOP CDM style).
